#!/bin/bash

counter=1

for file in *.{jpg,jpeg,png,gif}; do
    if [ -f "$file" ]; then
        extension="${file##*.}"
        new_name="i$(printf "%03d" "$counter").$extension"
        mv "$file" "$new_name"
        ((counter++))
    fi
done

