#!/bin/bash
# credits to Jakoolit for nvidia drivers part
if [ "$EUID" -eq 0 ]; then
    echo "run this script as a regular user, not as root."
    exit 1
fi

# update system
sudo pacman -Syu --noconfirm

# install yay
if ! command -v yay &> /dev/null; then
    echo "yay is not installed, installing yay"
    git clone https://aur.archlinux.org/yay.git $HOME/.local/yay
    cd $HOME/.local/yay
    makepkg -si
    echo "yay installed"
fi

# check whether the user has an nvidia GPU
nvidia_present=false
if lspci | grep -i nvidia &> /dev/null; then
    nvidia_present=true
fi

# install nvidia drivers if nvidia GPU is present
if [ "$nvidia_present" = true ]; then
    echo "NVIDIA GPU detected. Installing NVIDIA drivers."
    yay -S --noconfirm nvidia-dkms nvidia-settings nvidia-utils libva libva-nvidia-driver-git

    # check if the Nvidia modules are already added in mkinitcpio.conf and add if not
    if grep -qE '^MODULES=.*nvidia. *nvidia_modeset.*nvidia_uvm.*nvidia_drm' /etc/mkinitcpio.conf; then
        echo "Nvidia modules already included in /etc/mkinitcpio.conf" 2>&1 
    else
        sudo sed -Ei 's/^(MODULES=\([^\)]*)\)/\1 nvidia nvidia_modeset nvidia_uvm nvidia_drm)/' /etc/mkinitcpio.conf 2>&1 
        echo "Nvidia modules added in /etc/mkinitcpio.conf"
    fi

    sudo mkinitcpio -P 2>&1 
    printf "\n\n\n"

    # additional Nvidia steps
    NVEA="/etc/modprobe.d/nvidia.conf"
    if [ -f "$NVEA" ]; then
        printf "Seems like nvidia-drm modeset=1 is already added in your system..moving on.\n"
        printf "\n"
    else
        printf "\n"
        printf "Adding options to $NVEA..."
        sudo echo -e "options nvidia-drm modeset=1" | sudo tee -a /etc/modprobe.d/nvidia.conf 2>&1 
        printf "\n"
    fi

    # blacklist nouveau
    NOUVEAU="/etc/modprobe.d/nouveau.conf"
    if [ -f "$NOUVEAU" ]; then
        printf "Seems like nouveau is already blacklisted..moving on.\n"
    else
        printf "\n"
        echo "blacklist nouveau" | sudo tee -a "$NOUVEAU" 2>&1 
        printf "\n"

        if [ -f "/etc/modprobe.d/blacklist.conf" ]; then
            echo "install nouveau /bin/true" | sudo tee -a "/etc/modprobe.d/blacklist.conf" 2>&1 
        else
            echo "install nouveau /bin/true" | sudo tee "/etc/modprobe.d/blacklist.conf" 2>&1 
        fi
    fi
else
    echo "No NVIDIA GPU detected. No action taken."
fi

# asus rog packages options
read -p "Do you want to install the rog packages? (y/n): " user_input
if [[ "$user_input" == "y" || "$user_input" == "Y" ]]; then
    echo "Installing rog package..."
    yay -S --noconfirm asusctl supergfxd
    echo "ROG packages installation complete."
    printf " Activating ROG services...\n"
    sudo systemctl enable --now supergfxd 2>&1
else
    echo "User chose not to install 'rog' package. Exiting."
fi

echo "Installing needed packages..."
yay -S --noconfirm - < packages.txt

echo "Installing optional packages..."
yay -S --noconfirm - < optional.txt
chsh -s $(which zsh)

sudo systemctl enable --now bluetooth
sudo systemctl enable --now auto-cpufreq
systemctl mask power-profiles-daemon.service

cp .config $HOME/ -r
cp .zlogin $HOME/ 
cp .zshrc $HOME/

zsh
esac